name: Java CI

on: [push]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Set up PATH
      run: echo "${ANDROID_HOME}/build-tools/34.0.0" >> $GITHUB_PATH

    - name: General information
      run: |
        java --version
        d8 --version

    - name: Build and dexify mod jar file
      run: |
        chmod +x gradlew
        ./gradlew main:deploy main:dex tools:proc

    - name: Upload built mod jar file
      uses: actions/upload-artifact@v4
      with:
        name: ProjectUnity (zipped)
        path: main/build/libs/ProjectUnity.jar
        retention-days: 3